onlyBuiltDependencies:
  - '@carbon/charts'
  - '@carbon/charts-svelte'
  - '@carbon/colors'
  - '@carbon/utils-position'
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - esbuild
  - sharp
  - sqlite3

overrides:
  '@sveltejs/kit@>=2.19.0 <=2.49.4': '>=2.49.5'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  cookie@<0.7.0: '>=0.7.0'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  qs@<6.14.1: '>=6.14.1'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
